// #Sireum
package org.sireum.hamr.codegen.common.templates

import org.sireum._

@enum object CommentStyle {
  "Slash" // '//'
  "Hash"  // '#'
  "Xml"   // '<!--'
  "Smt2"  // ';'
  "Block" // '/*
  "NoComment"
}

object CommentTemplate {
  val doNotEditComment: String = "Do not edit this file as it will be overwritten if HAMR codegen is rerun"

  val noOverwriteDirective: String = "hamr:no-overwrite"

  val noOverwriteDirective_slash: String = s"//@ $noOverwriteDirective"
  val noOverwriteDirective_hash: String = s"#@ $noOverwriteDirective"
  val noOverwriteDirective_xml: String = s"<!--@ $noOverwriteDirective -->"
  val noOverwriteDirective_smt2: String = s";@ $noOverwriteDirective"
  val noOverwriteDirective_block: String = s"/* $noOverwriteDirective */"

  val doNotEditComment_slash: String = s"// $doNotEditComment\n// To prevent overwriting, add '${noOverwriteDirective_slash}' to this file"

  val doNotEditComment_hash: String = s"# $doNotEditComment\n# To prevent overwriting, add '${noOverwriteDirective_hash}' to this file"

  val doNotEditComment_xml: String = s"<!-- $doNotEditComment\n     To prevent overwriting, add a comment containing '@ $noOverwriteDirective' to this file -->"

  val doNotEditComment_smt2: String = s"; $doNotEditComment\n; To prevent overwriting, add '${noOverwriteDirective_smt2}' to this file"

  @strictpure def noOverwriteLinePrefix(style: CommentStyle.Type): String = style match {
    case CommentStyle.Slash => noOverwriteDirective_slash
    case CommentStyle.Hash => noOverwriteDirective_hash
    case CommentStyle.Xml => noOverwriteDirective_xml
    case CommentStyle.Smt2 => noOverwriteDirective_smt2
    case CommentStyle.NoComment => noOverwriteDirective
    case CommentStyle.Block => noOverwriteDirective_block
  }





  val safeToEditComment: String = "This file will not be overwritten if HAMR codegen is rerun"

  val safeToEditComment_slash: String = s"// $safeToEditComment"

  val safeToEditComment_hash: String = s"# $safeToEditComment"

  val safeToEditComment_xml: String = s"<!-- $safeToEditComment -->"

  val safeToEditComment_dts: String = s"/* $safeToEditComment */" // some parsers may not support '//'




  val invertedMarkerComment: String = "Content between markers will be preserved if codegen is rerun"

  val invertedMarkerComment_slash: String = s"// $invertedMarkerComment"

  val invertedMarkerComment_hash: String = s"# $invertedMarkerComment"

  val invertedMarkerComment_xml: String = s"<!-- $invertedMarkerComment -->"
}
