// #Sireum
package org.sireum.hamr.codegen.common.templates

import org.sireum._

object CommentTemplate {
  val doNotEditComment: String = "Do not edit this file as it will be overwritten if HAMR codegen is rerun"

  val doNotEditComment_slash: String = s"// $doNotEditComment"

  val doNotEditComment_hash: String = s"# $doNotEditComment"

  val doNotEditComment_xml: String = s"<!-- $doNotEditComment -->"

  val doNotEditComment_smt2: String = s"; $doNotEditComment"




  val safeToEditComment: String = "This file will not be overwritten if HAMR codegen is rerun"

  val safeToEditComment_slash: String = s"// $safeToEditComment"

  val safeToEditComment_hash: String = s"# $safeToEditComment"

  val safeToEditComment_xml: String = s"<!-- $safeToEditComment -->"

  val safeToEditComment_dts: String = s"/* $safeToEditComment */" // some parsers may not support '//'




  val invertedMarkerComment: String = "Content between markers will be preserved if codegen is rerun"

  val invertedMarkerComment_slash: String = s"// $invertedMarkerComment"

  val invertedMarkerComment_hash: String = s"# $invertedMarkerComment"

  val invertedMarkerComment_xml: String = s"<!-- $invertedMarkerComment -->"
}
