// #Sireum
package org.sireum.hamr.codegen.common.templates

import org.sireum._

object CommentTemplate {
  def doNotEditComment_code: String = {
    return "// Do not edit this file as it will be overwritten if HAMR codegen is rerun"
  }

  def doNotEditComment_c: String = {
    return doNotEditComment_code
  }

  def doNotEditComment_scala: String = {
    return doNotEditComment_code
  }

  def doNotEditComment_script: String = {
    return "# Do not edit this file as it will be overwritten if HAMR codegen is rerun"
  }

  def doNotEditComment_bash: String = {
    return doNotEditComment_script
  }

  def doNotEditComment_cmake: String = {
    return doNotEditComment_script
  }

  def safeToEditComment_code: String = {
    return "// This file will not be overwritten so is safe to edit"
  }

  def safeToEditComment_c: String = {
    return safeToEditComment_code
  }

  def safeToEditComment_scala: String = {
    return safeToEditComment_code
  }

  def safeToEditComment_script: String = {
    return "# This file will not be overwritten so is safe to edit"
  }

  def safeToEditComment_cmake: String = {
    return safeToEditComment_script
  }

  def safeToEditComment_bash: String = {
    return safeToEditComment_script
  }

}
